name: Compilar YiyoOverlay

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compilar DLL con MSVC
      run: |
        cl.exe /O2 /LD /std:c++17 /EHsc dllmain.cpp hook_dx11.cpp hook_dx12.cpp metrics.cpp /link /OUT:YiyoOverlay.dll d3d11.lib d3d12.lib dxgi.lib pdh.lib powrprof.lib user32.lib

    - name: Subir DLL Compilada
      uses: actions/upload-artifact@v4
      with:
        name: YiyoOverlay-DLL
        path: YiyoOverlay.dll
